# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Datadoc Unit tests

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Print Poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          poetry install --all-extras
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run pflake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run pflake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests
        run: |
          set -o pipefail; poetry run pytest -v --cache-clear --junitxml=pytest.xml --cov-report=term-missing --cov=datadoc | tee pytest-coverage.txt
      - name: Pytest coverage comment
        id: coverageComment
        # Always run
        if: ${{ success() || failure() }}
        uses: MishaKav/pytest-coverage-comment@main
        with:
          github-token: ${{github.token}}
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
      - name: Generate README Badge
        # Always run
        if: ${{ success() || failure() }}
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.COVERAGE_BADGE_GIST }}
          gistID: 0c0c5bdfc360b59254f2c32d65914025
          filename: pytest-coverage-badge-datadoc.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
